<?php

// 設定項目を定義
$GLOBALS['setting_title'] = [
    'basis'      => '基本設定',
    'entry'      => 'エントリー設定',
    'page'       => 'ページ設定',
    'comment'    => 'コメント設定',
    'user'       => 'ユーザー設定',
    'restricted' => '制限設定',
    'number'     => '表示件数設定',
    'menu'       => 'メニュー設定',
    'text'       => '文言設定',
    'mail'       => 'メール設定',
];
$GLOBALS['setting_contents'] = [
    'basis' => [
        'title' => [
            'name'        => 'タイトル',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'description' => [
            'name'        => '概要',
            'explanation' => null,
            'type'        => 'text',
            'required'    => false,
        ],
        'admin_title' => [
            'name'        => '管理ページ タイトル',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'admin_description' => [
            'name'        => '管理ページ 概要',
            'explanation' => null,
            'type'        => 'text',
            'required'    => false,
        ],
    ],
    'entry' => [
        'entry_use_approve' => [
            'name'        => 'エントリーの承認',
            'explanation' => '公開には管理者の承認が必要になります。',
            'type'        => 'boolean',
            'required'    => false,
        ],
        'entry_use_picture' => [
            'name'        => '写真の入力',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'entry_use_thumbnail' => [
            'name'        => 'サムネイルの入力',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'entry_default_code' => [
            'name'        => 'コードの初期値',
            'explanation' => 'YmdHisが年月日時分秒になります。',
            'type'        => 'text',
            'required'    => false,
        ],
        'entry_text_type' => [
            'name'        => '本文の入力項目',
            'explanation' => null,
            'type'        => 'select',
            'required'    => false,
            'kind'        => [
                'none'     => 'なし',
                'textarea' => '複数行入力',
                'html'     => 'HTML直接入力',
                'wysiwyg'  => 'WYSIWYGエディタ',
            ],
        ],
    ],
    'page' => [
        'page_use_approve' => [
            'name'        => 'ページの承認',
            'explanation' => '公開には管理者の承認が必要になります。',
            'type'        => 'boolean',
            'required'    => false,
        ],
        'page_use_picture' => [
            'name'        => '写真の入力',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'page_use_thumbnail' => [
            'name'        => 'サムネイルの入力',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'page_default_code' => [
            'name'        => 'コードの初期値',
            'explanation' => 'YmdHisが年月日時分秒になります。',
            'type'        => 'text',
            'required'    => false,
        ],
        'page_text_type' => [
            'name'        => '本文の入力項目',
            'explanation' => null,
            'type'        => 'select',
            'required'    => false,
            'kind'        => [
                'none'     => 'なし',
                'textarea' => '複数行入力',
                'html'     => 'HTML直接入力',
                'wysiwyg'  => 'WYSIWYGエディタ',
            ],
        ],
        'page_home_code' => [
            'name'        => 'ホームページに表示するページのコード',
            'explanation' => '指定したコードのページがホームページに表示されます。',
            'type'        => 'text',
            'required'    => false,
        ],
        'page_url_omission' => [
            'name'        => 'ページURLの省略',
            'explanation' => '「page/」を省略してページへアクセスできるようにします。',
            'type'        => 'boolean',
            'required'    => false,
        ],
    ],
    'comment' => [
        'comment_use_approve' => [
            'name'        => 'コメントの承認',
            'explanation' => '公開には管理者の承認が必要になります。',
            'type'        => 'boolean',
            'required'    => false,
        ],
    ],
    'user' => [
        'user_use_register' => [
            'name'        => '訪問者によるユーザー新規登録',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'user_use_approve' => [
            'name'        => 'ユーザーの承認',
            'explanation' => 'ログインには管理者の承認が必要になります。',
            'type'        => 'boolean',
            'required'    => false,
        ],
    ],
    'restricted'  => [
        'restricted_password_title' => [
            'name'        => 'パスワード認証で制限されたタイトルの先頭に付与する文字列',
            'explanation' => null,
            'type'        => 'text',
            'required'    => false,
        ],
        'restricted_password_text' => [
            'name'        => 'パスワード認証で制限された本文に表示する文言',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
    ],
    'number' => [
        'number_limit_entry' => [
            'name'        => 'エントリーの表示件数',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_contact' => [
            'name'        => 'お問い合わせの表示件数',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_comment' => [
            'name'        => 'コメントの表示件数',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_home_entry' => [
            'name'        => 'エントリーの表示件数（ホームページ）',
            'explanation' => '0にすると項目自体が非表示になります。',
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_admin_entry' => [
            'name'        => 'エントリーの表示件数（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_admin_contact' => [
            'name'        => 'お問い合わせの表示件数（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_admin_comment' => [
            'name'        => 'コメントの表示件数（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_admin_user' => [
            'name'        => 'ユーザーの表示件数（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_limit_admin_log' => [
            'name'        => 'ログの表示件数（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_entry' => [
            'name'        => 'エントリーのページャー幅',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_contact' => [
            'name'        => 'お問い合わせのページャー幅',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_comment' => [
            'name'        => 'コメントのページャー幅',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_admin_entry' => [
            'name'        => 'エントリーのページャー幅（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_admin_contact' => [
            'name'        => 'お問い合わせのページャー幅（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_admin_comment' => [
            'name'        => 'コメントのページャー幅（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_admin_user' => [
            'name'        => 'ユーザーのページャー幅（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
        'number_width_admin_log' => [
            'name'        => 'ログのページャー幅（管理ページ）',
            'explanation' => null,
            'type'        => 'number',
            'required'    => true,
        ],
    ],
    'menu' => [
        'menu_auth' => [
            'name'        => 'ユーザーメニューに「ログイン」を表示',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'menu_admin_field' => [
            'name'        => '管理メニューに「フィールド」を表示',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'menu_admin_menu' => [
            'name'        => '管理メニューに「メニュー」を表示',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
        'menu_admin_widget' => [
            'name'        => '管理メニューに「ウィジェット」を表示',
            'explanation' => null,
            'type'        => 'boolean',
            'required'    => false,
        ],
    ],
    'text' => [
        'text_home_index' => [
            'name'        => 'トップページ',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_entry_index' => [
            'name'        => 'エントリー',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_entry_detail' => [
            'name'        => 'エントリー 詳細',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_entry_detail_comment_form' => [
            'name'        => 'エントリー コメント投稿',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_page_index' => [
            'name'        => 'ページ',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_page_index_comment_form' => [
            'name'        => 'ページ コメント投稿',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_contact_index' => [
            'name'        => 'お問い合わせ',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_contact_preview' => [
            'name'        => 'お問い合わせ 確認',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_contact_complete' => [
            'name'        => 'お問い合わせ 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_comment_preview' => [
            'name'        => 'コメント投稿 確認',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_comment_complete' => [
            'name'        => 'コメント投稿 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_index' => [
            'name'        => 'ログイン',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_register' => [
            'name'        => 'ユーザー登録',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_register_preview' => [
            'name'        => 'ユーザー登録 確認',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_register_complete' => [
            'name'        => 'ユーザー登録 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_password' => [
            'name'        => 'パスワード再設定',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_password_form' => [
            'name'        => 'パスワード再設定 登録',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_password_complete' => [
            'name'        => 'パスワード再設定 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_home' => [
            'name'        => 'マイページ',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_contact' => [
            'name'        => 'お問い合わせ履歴',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_comment' => [
            'name'        => 'コメント履歴',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_comment_form' => [
            'name'        => 'コメント登録',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_modify' => [
            'name'        => 'ユーザー情報編集',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_modify_preview' => [
            'name'        => 'ユーザー情報編集 確認',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_modify_complete' => [
            'name'        => 'ユーザー情報編集 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_leave' => [
            'name'        => 'ユーザー情報削除',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_leave_confirm' => [
            'name'        => 'ユーザー情報削除 確認',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
        'text_auth_leave_complete' => [
            'name'        => 'ユーザー情報削除 完了',
            'explanation' => null,
            'type'        => 'textarea',
            'required'    => false,
        ],
    ],
    'mail' => [
        'mail_from' => [
            'name'        => 'メールの送信元',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_to' => [
            'name'        => 'メールの送信先',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_body_begin' => [
            'name'        => 'メール本文の冒頭',
            'explanation' => 'すべてのメール本文の冒頭に挿入されます。',
            'type'        => 'textarea',
            'required'    => false,
        ],
        'mail_body_end' => [
            'name'        => 'メール本文の末尾',
            'explanation' => 'すべてのメール本文の末尾に挿入されます。',
            'type'        => 'textarea',
            'required'    => false,
        ],
        'mail_register_subject' => [
            'name'        => 'ユーザー登録完了メールの件名',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_verify_subject' => [
            'name'        => 'メールアドレス存在確認メールの件名',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_password_subject' => [
            'name'        => 'パスワード再設定メールの件名',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_leave_subject' => [
            'name'        => 'ユーザー削除完了メールの件名',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_contact_subject' => [
            'name'        => 'お問い合わせメールの件名',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
        'mail_contact_subject_admin' => [
            'name'        => 'お問い合わせメールの件名（管理者用）',
            'explanation' => null,
            'type'        => 'text',
            'required'    => true,
        ],
    ],
];
