<?php

// 文字列を定義
$GLOBALS['string'] = [
    'heading_menu'           => 'メニュー',
    'heading_entry_list'     => 'エントリー',
    'heading_entry_recently' => 'エントリー',
    'heading_entry_page'     => 'ページ',
    'heading_contact_form'   => 'お問い合わせ',
    'heading_comment_list'   => 'コメント',
    'heading_comment_form'   => 'コメント投稿',
    'heading_category_list'  => 'カテゴリー',
    'heading_archive_list'   => 'アーカイブ',
    'heading_auth'           => 'ログイン',
    'heading_register'       => 'ユーザー登録',
    'heading_password'       => 'パスワード再設定',
    'heading_mypage'         => 'マイページ',
    'heading_user'           => 'ユーザー情報',

    'menu_public_home'    => 'ホーム',
    'menu_public_entry'   => 'エントリー',
    'menu_public_contact' => 'お問い合わせ',
    'menu_public_auth'    => 'ログイン',
    'menu_auth_contact'   => 'お問い合わせ履歴',
    'menu_auth_comment'   => 'コメント履歴',
    'menu_auth_modify'    => 'ユーザー情報編集',
    'menu_auth_leave'     => 'ユーザー情報削除',
    'menu_auth_logout'    => 'ログアウト',

    'text_entry_continue' => 'エントリーを読む',
    'text_category_all'   => '全て',
    'text_goto_home'      => 'ホームページへ戻る',
    'text_goto_auth'      => 'ログインページへ戻る',
    'text_goto_auth_home' => 'マイページホームへ戻る',
    'text_goto_entry'     => '戻る',

    'button_password'              => '認証',
    'button_comment'               => '投稿',
    'button_comment_confirm'       => '投稿',
    'button_comment_delete'        => '削除',
    'button_auth_login'            => 'ログイン',
    'button_auth_leave'            => '削除',
    'button_auth_leave_confirm'    => '進む',
    'button_auth_modify'           => '登録',
    'button_auth_modify_confirm'   => '確認',
    'button_auth_password'         => '登録',
    'button_auth_password_confirm' => '再設定',
    'button_auth_register'         => '登録',
    'button_auth_register_confirm' => '確認',
    'button_auth_contact'          => '送信',
    'button_auth_contact_confirm'  => '確認',
];
